FROM nginx:alpine

# Copy the pre-compiled Angular output directly (relative to the context)
COPY browser /usr/share/nginx/html

# Copy the Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
