# Configuration de la base de données
spring.datasource.url=jdbc:postgresql://localhost:5435/grh_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Upload de fichiers (Dossier du personnel)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Configuration Sécurité & JWT
# Clé secrète de signature HMAC-SHA256 (doit faire au moins 256 bits / 32 caractères de long)
# "Gj5pX92sKz8wV1a4m7d8f9g0hJkLmNpQrStUvWxYz1234567890abcdefghijklmnopqrstuv"
app.jwt.secret=Gj5pX92sKz8wV1a4m7d8f9g0hJkLmNpQrStUvWxYz1234567890abcdefghijklmnopqrstuv
# Expiration du token (24 heures en millisecondes = 86400000)
app.jwt.expiration-ms=86400000

# Paramétrage de l'administration par défaut
app.default-administration.name-ar=\u0627\u0644\u0645\u062f\u0631\u0633\u0629 \u0627\u0644\u0648\u0637\u0646\u064a\u0629 \u0644\u062a\u0643\u0648\u064a\u0646 \u0625\u0637\u0627\u0631\u0627\u062a \u0627\u0644\u0623\u0645\u0646 \u0627\u0644\u0648\u0637\u0646\u064a \u0648\u0627\u0644\u0634\u0631\u0637\u0629 \u0627\u0644\u0648\u0637\u0646\u064a\u0629 \u0628\u0635\u0644\u0627\u0645\u0628\u0648
app.default-administration.name-fr=Ecole Nationale de Formation des Cadres de la Surete Nationale et de la Police Nationale de Carthage Salambo
app.default-administration.code=ENFCSPN

# Configuration Serveur
server.port=8080
# server.servlet.context-path=/api

# Configuration Stockage d'objets (MinIO / S3)
aws.s3.endpoint=${S3_ENDPOINT:http://localhost:9000}
aws.s3.access-key=${S3_ACCESS_KEY:admin}
aws.s3.secret-key=${S3_SECRET_KEY:supersecretpassword}
aws.s3.bucket-name=${S3_BUCKET:grh-pictures}
